### ISSUE TITLE
Dockerfile Type-o?

### ISSUE THREAD

**Issue by heymoe** [linuxserver/docker-hydra2#1]
I'm pretty sure you need to 

EXPOSE 5076

and not 

EXPOSE 5075

in your Dockerfile

**Comment by sparklyballs** [comment]
the Dockerfile doesn't actually publish the port the run line does and as such it doesn't really matter what the Dockerfile says

**Comment by heymoe** [comment]
No doubt this does not effect how this docker runs since it does run fine BUT I would say that this incorrect setting in the dockerfile does allocate / open a port in the container that doesn't need to be open.

My command line only contains: `-p 5076:5076` in it but doing a `docker ps` of the running container shows this:

`linuxserver/hydra2:latest   "/init"                  6 days ago          Up 6 days             5075/tcp, 0.0.0.0:5076->5076/tcp`

As you can see docker is exposing 5075 because that is what the dockerfile is telling docker to do.

Plus, this is a single character change to your docker file, why not just fix it?

**Comment by hanatokitsu** [comment]
@heymoe is right. This beaks things like automatic service port detection in traefik.
