### ISSUE TITLE
Update to Java 10

### ISSUE THREAD

**Issue by theotherp** [linuxserver/docker-hydra2#10]
Hi,

the latest release works with Java 10. Apparently there have been made some changes to improve Java under docker with Java 10. Would be nice if you could update the container.

**Comment by sparklyballs** [comment]
there is an extra set of warnings with java 10

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/app/hydra2/lib/core-2.0.0-exec.jar!/BOOT-INF/lib/spring-core-5.0.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by theotherp** [comment]
You can ignore that... I'll try to hide it in the next release.

**Comment by CurlyFlow** [comment]
I have exact the same (?), but i cant login anymore to hydra and also radarr and sonarr cant connect anymore.

Also maxing my CPU at 100%. (bc it tries to restart after every crash)

[nzbhydra2.log](https://github.com/linuxserver/docker-hydra2/files/2794333/nzbhydra2.log)
