### ISSUE TITLE
Update to v2.0.9

### ISSUE THREAD

**Issue by otherguy** [linuxserver/docker-hydra2#12]
Hey guys,

will you update to the latest v2.0.9 release of Hydra2?

**Comment by j0nnymoe** [comment]
Already is: 
![image](https://user-images.githubusercontent.com/10374553/46679825-aae3c700-cbdf-11e8-9bea-0aeef2799a16.png)
Pull the latest image and recreate your container.

**Comment by otherguy** [comment]
@j0nnymoe weird 🤔 That's what I did and it's what I always do. I have it running on a Synology NAS that has a terribly slow image download process. Maybe I was too fast with recreating the container and the image wasn't fully downloaded yet... I just re-created the container again and it's working fine!

Thank you and sorry for bothering you. Keep up the great work! 👍 🙂
