### ISSUE TITLE
CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'

### ISSUE THREAD

**Issue by nomandera** [linuxserver/docker-hydra2#14]
Using our Letsencrypt container with our reverse proxy stanza and basic HTTP auth this upstream config change is required

https://github.com/theotherp/nzbhydra2/issues/54

It may be best just fixing this in documentation although a hands off universal fix would be better.

**Comment by aptalca** [comment]
Does this only affect the subfolder method or subdomain as well?

**Comment by nomandera** [comment]
TBH I dont know we would need to test

**Comment by aptalca** [comment]
Alright, I did some tests and it seems to only affect the subfolder method. But the hydra2 gui now has a setting for turning CSRF protection off. I PR'ed an info update for the subfolder proxy conf: https://github.com/linuxserver/reverse-proxy-confs/pull/15

**Comment by nomandera** [comment]
Confirmed that existing manual disabling of CSRF protection shows correct in new hydra (i.e. it stays off and is shown as off).

Great result. Nice work  aptalca.
