### ISSUE TITLE
Constantly restarting 

### ISSUE THREAD

**Issue by CurlyFlow** [linuxserver/docker-hydra2#16]
Constantly restarting, cant access it via http, radarr and sonarr also cant reach it.
	

 
unraid 6.6

<img width="1188" alt="123" src="https://user-images.githubusercontent.com/43281991/51719924-b1d9fc80-204b-11e9-9592-89b7eeedffea.png">
[nzbhydra2.log](https://github.com/linuxserver/docker-hydra2/files/2794344/nzbhydra2.log)

**Comment by thelamer** [comment]
I am unable to duplicate this even with bad permissions on the config directory ETC, so there must be config files present in that appdata folder either from a previous install or something host level. 

The fastest fix is to recreate that directory and re-configure your application likely. 

Let me know if that is the case.

**Comment by CurlyFlow** [comment]
Hmm... i just renamed all files in database (whats in there, pretty big btw 1,8gb)

and it seems to work again...?

Do i need to setup anything else? seems to work tho.

What i also noticed is 4000+ (2gb) files in log directory... could that be automatic cleaned?

**Comment by thelamer** [comment]
It sounds like you are up and running. 
I am going to close this issue, if you have any ideas for log rotation please open a new issue.
