### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by CurlyFlow** [linuxserver/docker-hydra2#17]
Hey, it would be cool if the log directory would be automatic deleted, maybe save X days, or 30 logs, or what ever, it was grown to over 4000 files (2gb) until i noticed.

Also i dont know if the .db gets cleared at some time, if not, that would be also cool.

**Comment by aptalca** [comment]
Hydra logs already seem to have some kind of log rotation built in, but it is entirely managed by hydra and not our image. You should report on their github
