### ISSUE TITLE
Use OpenJDK J9 to reduce memory usage

### ISSUE THREAD

**Issue by theotherp** [linuxserver/docker-hydra2#18]
A while ago I updated my own container to use a different JVM which reduces memory usage. I haven't heard of any problems and haven't encountered any myself. If possible you could use that in your container. See https://github.com/theotherp/nzbhydra2/blob/master/misc/docker/Dockerfile

**Comment by homerr** [comment]
This container is built with the latest OpenJDK version as available for Ubuntu Bionic, so for reasons of ensuring reliable support, we'll be keeping this one as it is.

**Comment by sparklyballs** [comment]
@homer , @theotherp is the dev for hydra.

**Comment by emopinata** [comment]
> @homer , @theotherp is the dev for hydra.
> […](#)
> On 27 Feb 2019, at 14:47, Homer ***@***.***> wrote: Closed #18. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

@homerr, I'm with @sparklyballs, I'd take the recommendation seriously. Since it doesn't seem like bionic has 9 anymore, it looks like the options may be either using the openjdk-r ppa or pulling the binary and installing manually.

**Comment by aptalca** [comment]
I looked into it and it seems the recommended version is not openjdk9 but is a custom v8 build that is called `Eclipse OpenJ9`. I have no experience with that but will look into it.

**Comment by emopinata** [comment]
@aptalca I'm taking a stab at it as we speak

**Comment by emopinata** [comment]
At least, I'm looking it over. Will likely need to do something like the curl/awk for the hydra2 release from the Github API for the correct OpenJ9 version...

https://api.github.com/repos/AdoptOpenJDK/openjdk8-binaries/releases (if this is the version you were talking about)

**Comment by sparklyballs** [comment]
@jalmansor that's not multi-arch though

at least not , aarch64 and armhf anyways..

not particularly viable for us.

**Comment by emopinata** [comment]
@sparklyballs you're right, I see that they don't have the necessary archs in the 8 build, but they do in the 11. Ugh...

https://github.com/AdoptOpenJDK/openjdk-build#build-status

Might have to take a stab at building it myself.

**Comment by homerr** [comment]
cheers @sparklyballs and sorry @theotherp I'm unfamiliar with this project, hope no offence caused. 

Is this now in a state where we can't progress (for multi arch, at least) without building the binaries ourselves?

**Comment by emopinata** [comment]
I think another option might be to rebase on Alpine, which uses the [IcedTea](https://icedtea.classpath.org/wiki/Main_Page) build of OpenJDK, though I'm unsure yet if this version provides the same benefits as OpenJ9. @theotherp's own Dockerfile uses an Alpine base, which I'm assuming works fine.

**Comment by thelamer** [comment]
@theotherp Thanks for the heads up, but unfortunately the J9 JVM you are using is not built for arm and aarch64. 
https://github.com/AdoptOpenJDK/openjdk9-openj9-releases/releases
We also do not have the option to compile it ourselves: 
https://github.com/eclipse/omr/issues/2327

Also from a Docker standpoint the Alpine image you are using Hacks in GLIBC: 
https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/9/jdk/alpine/Dockerfile.openj9.releases.slim

There is nothing inherently wrong with doing this, but my personal recommendation would be to swap to their Ubuntu base image. 

Sorry for letting this sit for such a long period of time, as it stands now providing seemless support for arm and aarch platforms is a core goal of ours.
