### ISSUE TITLE
NZBHydra2 not starting - An unexpected error occurred during startup,

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-hydra2#23]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Hydra2 should start

## Current Behavior
Unable to start since latest version

## Steps to Reproduce

1. Loaded NZBHydra2, unable to access site. 
2. Tried recreating with latest, didn't work. 
3. Reverted back to hydra2:v2.9.4-ls44 and this did work

## Environment
**OS:**   Fedora 27
**CPU architecture:** x86_64
**Docker**
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=hydra2 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 5076:5076 \
  -v NZBHydra2:/config \
  -v /var/hda/files/drives/drive12/downloads:/downloads \
  --restart unless-stopped \
  linuxserver/hydra2

## Docker logs

> org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp,
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51),
> Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp,
> 	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:180),
> 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:178),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
> Caused by: java.io.IOException: Permission denied,
> 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method),
> 	at java.base/java.io.File.createTempFile(File.java:2090),
> 	at java.base/java.io.File.createTempFile(File.java:2136),
> 	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:172),
> 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:178),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> ,
> 2019-11-23 23:49:34.833 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup,
> ,
> org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp,
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51),
> Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp,
> 	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:180),
> 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:178),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
> Caused by: java.io.IOException: Permission denied,
> 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method),
> 	at java.base/java.io.File.createTempFile(File.java:2090),
> 	at java.base/java.io.File.createTempFile(File.java:2136),
> 	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:172),
> 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:178),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153),
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544),
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141),
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747),
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315),
> 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:167),
> 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:119),
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
> ,

**Comment by aptalca** [comment]
Please post a full docker log to pastebin and drop the link here

**Comment by modem7** [comment]
https://pastebin.com/vzZ1GBFx

Is this what you're looking for? Sorry, still new to Docker and it's logs!

This is from the reverted 2.9.4 version: https://pastebin.com/i4GU9SXF

**Comment by j0nnymoe** [comment]
![image](https://user-images.githubusercontent.com/10374553/69500620-956d5180-0ef4-11ea-95cb-b4cd49977cff.png)
Can confirm newest build is working. Update to the newest build but then restore a working backup of your hydra2 appdata.

**Comment by modem7** [comment]
Can confirm it's now all working. Unsure what was going on.

Thanks!
