### ISSUE TITLE
 Add support for prereleases

### ISSUE THREAD

**Issue by theotherp** [linuxserver/docker-hydra2#25]
I'll add support for prereleases in the next version. These can be determined by the property `prerelease` of the GitHub release (e.g. https://api.github.com/repos/theotherp/nzbhydra2/releases/latest).

Would it be possible for the regular container to not update to these and add a new container or tag for the latest prerelease? 

To be honest I'm not aware of the build process and even how the containers are installed, so I'm not sure if this would even be possible.

Thanks!

**Comment by aptalca** [comment]
Sure, we can do that. We can track those with a `dev` tag on docker hub as opposed to `latest` so users can pull them via `linuxserver/hydra2:dev` or the specific version tag.

Thanks for letting us know.

**Comment by theotherp** [comment]
If that helps, hotio already [made the changes](https://github.com/hotio/docker-nzbhydra2/commits/master) - but his build process is probably different. He uses the tags "latest" and stable vs. "unstable". I don't really care about the names, though.

Thanks.

**Comment by aptalca** [comment]
@theotherp when you do a prerelease, please let us know here or on discord and we'll merge #26 

Thanks

**Comment by theotherp** [comment]
The latest release is currently a prerelease.

**Comment by aptalca** [comment]
Thanks. The `dev` tag is now live

**Comment by bablat** [comment]
@aptalca minor suggestion here:
I believe you selected the last release tagged with "prerelease", I think it would be wise to pick latest stable over latest prerelease if latest is newer.
I just switched from latetst to dev expecting bleeding edge v2.20, and got an older version v19.0 which did not even start with my newer configuration schema which was upgraded at some point and isn't backwards compatible apparently.
