### ISSUE TITLE
Permissions of /app/hydra2 causes updates to fail

### ISSUE THREAD

**Issue by claym** [linuxserver/docker-hydra2#3]
So, per https://github.com/theotherp/nzbhydra2/issues/92#issuecomment-371850299

The process fails due a permissioning error.

I dug around and noticed the process was running under "abc" but root owns /app/hydra2.

I chown'd the hydra2 directory to abc:abc and the update process works!

I'd recommend changing ownership of that directory unless there's a security reason not to. Looks like it's set up like this in other similar apps (mylar, headphones, etc)

**Comment by sparklyballs** [comment]
we absolutely do not support updates through the webui 

our image is both updated weekly and whenever a new release is issued by the developer
