### ISSUE TITLE
How can I set the Xmx Java heap size?

### ISSUE THREAD

**Issue by piejanssens** [linuxserver/docker-hydra2#6]
❔

**Comment by j0nnymoe** [comment]
In hydra config page.

**Comment by piejanssens** [comment]
It resets to 128 whenever I restart the application (using the hydra UI).
Edit: had to set it in the UI, not manually. 🥇

**Comment by sparklyballs** [comment]
i've just @j0nnymoe's advice and 

![screen shot 2018-05-03 at 20 52 52](https://user-images.githubusercontent.com/4343808/39599562-0932d9e8-4f14-11e8-8bd9-179ff3c9f79c.png)

**Comment by zxvv** [comment]
Note that for those using ansible playbooks, exposing the RUN_OPTS method of setting --xmx will significantly simplify it's usage.   Alternatively, modifying the config file entails both waiting for the container to create it, and after modifying it, waiting for the container to restart, which may contribute to other issues.

**Comment by sparklyballs** [comment]
easiest is using the webui by
